export default [
  {
    image:
      'https://d4t7t8y8xqo0t.cloudfront.net/resized/750X436/eazytrendz%2F1984%2Ftrend20180808073140.jpg',
    title: 'Fruit pizza',
    size: 'Medium',
    author: '@bkristastucchio',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 2,
    cols: 2,
    featured: true,
  },
  {
    image:
      'https://st.depositphotos.com/1003814/5052/i/950/depositphotos_50523105-stock-photo-pizza-with-tomatoes.jpg',
    title: 'Fruit pizza',
    author: '@rollelflex_graphy726',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 2,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1522770179533-24471fcdba45',
    title: 'Fruit pizza',
    author: '@helloimnik',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 2,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1444418776041-9c7e33cc5a9c',
    title: 'Fruit pizza',
    author: '@nolanissac',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1533827432537-70133748f5c8',
    title: 'Fruit pizza',
    author: '@hjrc33',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62',
    title: 'Fruit pizza',
    author: '@arwinneil',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1516802273409-68526ee1bdd6',
    title: 'Fruit pizza',
    author: '@tjdragotta',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1518756131217-31eb79b20e8f',
    title: 'Fruit pizza',
    author: '@katie_wasserman',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1597645587822-e99fa5d45d25',
    title: 'Fruit pizza',
    author: '@silverdalex',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1567306301408-9b74779a11af',
    title: 'Tomato basil',
    author: '@shelleypauls',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1471357674240-e1a485acb3e1',
    title: 'Fruit pizza',
    author: '@peterlaster',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
  {
    image: 'https://images.unsplash.com/photo-1589118949245-7d38baf380d6',
    title: 'Bike',
    author: '@southside_customs',
    Ingredients: 'Pineapple, Banana, Apple',
    rows: 3,
    cols: 2,
    featured: true,
  },
];
